package com.myspace.claimsconnect_rulesbase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class approvalLimit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("amount")
	private java.lang.Integer amount;
	@org.kie.api.definition.type.Label(value = "role")
	private java.util.List<java.lang.String> role;

	public approvalLimit() {
	}

	public java.lang.Integer getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Integer amount) {
		this.amount = amount;
	}

	public java.util.List<java.lang.String> getRole() {
		return this.role;
	}

	public void setRole(java.util.List<java.lang.String> role) {
		this.role = role;
	}

	public approvalLimit(java.lang.Integer amount,
			java.util.List<java.lang.String> role) {
		this.amount = amount;
		this.role = role;
	}

}