package com.myspace.claimsconnect_rulesbase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class dataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("task")
	private com.myspace.claimsconnect_rulesbase.caseObject task;
	@org.kie.api.definition.type.Label("claim")
	private com.myspace.claimsconnect_rulesbase.caseObject claim;

	@org.kie.api.definition.type.Label("caseType")
	private java.lang.String caseType;

	@org.kie.api.definition.type.Label("status")
	private java.lang.String status;

	@org.kie.api.definition.type.Label(value = "containerId")
	private java.lang.String containerId;

	@org.kie.api.definition.type.Label(value = "processId")
	private java.lang.String processId;

	@org.kie.api.definition.type.Label(value = "processInstanceId")
	private java.lang.String processInstanceId;

	public dataObject() {
	}

	public com.myspace.claimsconnect_rulesbase.caseObject getTask() {
		return this.task;
	}

	public void setTask(com.myspace.claimsconnect_rulesbase.caseObject task) {
		this.task = task;
	}

	public com.myspace.claimsconnect_rulesbase.caseObject getClaim() {
		return this.claim;
	}

	public void setClaim(com.myspace.claimsconnect_rulesbase.caseObject claim) {
		this.claim = claim;
	}

	public java.lang.String getCaseType() {
		return this.caseType;
	}

	public void setCaseType(java.lang.String caseType) {
		this.caseType = caseType;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getContainerId() {
		return this.containerId;
	}

	public void setContainerId(java.lang.String containerId) {
		this.containerId = containerId;
	}

	public java.lang.String getProcessId() {
		return this.processId;
	}

	public void setProcessId(java.lang.String processId) {
		this.processId = processId;
	}

	public java.lang.String getProcessInstanceId() {
		return this.processInstanceId;
	}

	public void setProcessInstanceId(java.lang.String processInstanceId) {
		this.processInstanceId = processInstanceId;
	}

	public dataObject(com.myspace.claimsconnect_rulesbase.caseObject task,
			com.myspace.claimsconnect_rulesbase.caseObject claim,
			java.lang.String caseType, java.lang.String status,
			java.lang.String containerId, java.lang.String processId,
			java.lang.String processInstanceId) {
		this.task = task;
		this.claim = claim;
		this.caseType = caseType;
		this.status = status;
		this.containerId = containerId;
		this.processId = processId;
		this.processInstanceId = processInstanceId;
	}

}