package com.myspace.claimsconnect_rulesbase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class notificationList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("notification")
	private java.util.List<com.myspace.claimsconnect_rulesbase.notification> notification;

	public notificationList() {
	}

	public java.util.List<com.myspace.claimsconnect_rulesbase.notification> getNotification() {
		return this.notification;
	}

	public void setNotification(
			java.util.List<com.myspace.claimsconnect_rulesbase.notification> notification) {
		this.notification = notification;
	}

	public notificationList(
			java.util.List<com.myspace.claimsconnect_rulesbase.notification> notification) {
		this.notification = notification;
	}

}