package com.myspace.claimsconnect_rulesbase;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class notification implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("notificationType")
	private java.lang.String notificationType;
	@org.kie.api.definition.type.Label("operatorCode")
	private java.lang.String operatorCode;
	@org.kie.api.definition.type.Label("referenceNumber")
	private java.lang.String referenceNumber;
	@org.kie.api.definition.type.Label("roleId")
	private java.lang.String roleId;

	@org.kie.api.definition.type.Label(value = "description")
	private java.lang.String description;

	public notification() {
	}

	public java.lang.String getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(java.lang.String notificationType) {
		this.notificationType = notificationType;
	}

	public java.lang.String getOperatorCode() {
		return this.operatorCode;
	}

	public void setOperatorCode(java.lang.String operatorCode) {
		this.operatorCode = operatorCode;
	}

	public java.lang.String getReferenceNumber() {
		return this.referenceNumber;
	}

	public void setReferenceNumber(java.lang.String referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	public java.lang.String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(java.lang.String roleId) {
		this.roleId = roleId;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public notification(java.lang.String notificationType,
			java.lang.String operatorCode, java.lang.String referenceNumber,
			java.lang.String roleId, java.lang.String description) {
		this.notificationType = notificationType;
		this.operatorCode = operatorCode;
		this.referenceNumber = referenceNumber;
		this.roleId = roleId;
		this.description = description;
	}

}